### ISSUE TITLE
did-key-ed25519 dependency on did-key-x25519

### ISSUE THREAD

**Issue by NickDarvey** [transmute-industries/did-key.js#44]
This might be due to my lack of webdev knowledge, so bear with me...

`@transmute/did-key-ed25519` [has a peer dependency on `@transmute/did-key-x25519`](https://github.com/transmute-industries/did-key.js/blob/28e7977d60b1074bfa8154cf83d9f6f97895e441/packages/ed25519/package.json#L27) `0.1.0` 

`@transmute/universal-wallet` also [has a peer depedency on `@transmute/did-key-x25519`](https://github.com/w3c-ccg/universal-wallet-interop-spec/blob/00bd90f158d2544bc6b69cdf126470831f8bef5f/packages/universal-wallet/package.json#L28) but on `^0.2.1-unstable.1`

Both of them [are dependencies](https://github.com/transmute-industries/sidetree.js/blob/27a679340fa5238a07e7f4ce842800c2f86527b8/packages/wallet/package.json#L35-L37) for `@sidetree/wallet` and I'm not sure how to resolve them when I add that package to my app.
```
npm install --save-dev "@transmute/did-key-x25519@...?"
```

Does `did-key-ed25519` really need both a peer dependency on `did-key-x25519` `0.1.0` and the regular dependency on `did-key-x25519` `{lerna version}`?

https://github.com/transmute-industries/did-key.js/blob/28e7977d60b1074bfa8154cf83d9f6f97895e441/packages/ed25519/package.json#L27

https://github.com/transmute-industries/did-key.js/blob/28e7977d60b1074bfa8154cf83d9f6f97895e441/packages/ed25519/package.json#L45

**Comment by OR13** [comment]
The reason is that ed25519 (the original did key type) is also used for x25519 (through public  / private key conversion)

https://github.com/transmute-industries/did-key.js/blob/master/packages/ed25519/src/Ed25519KeyPair.ts#L204

https://w3c-ccg.github.io/did-method-key/#create
https://w3c-ccg.github.io/did-method-key/#key-derivation-lacks-proof

**Comment by OR13** [comment]
I think the peer dependency part of this may not be correct, technically they should all use the latest version (there is not reason afaik they should be pinned to a lower version).
