### ISSUE TITLE
secp256k1: did is not resolved by Universal Resolver and on mobile (RN/expo)

### ISSUE THREAD

**Issue by alexkravets** [transmute-industries/did-key.js#66]
Locally (node environment) all tests do work file and all did's are resolved. But then on mobile (same code is used) and here in Universal Resolver (https://dev.uniresolver.io) did fails to resolve with error: `Error: Unsupported Fingerprint Type: zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn`

Locally resolved DID document:

```js
{
  '@context': [
    'https://www.w3.org/ns/did/v1',
    {
      '@base': 'did:key:zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn'
    }
  ],
  id: 'did:key:zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn',
  verificationMethod: [
    {
      id: '#zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn',
      type: 'EcdsaSecp256k1VerificationKey2019',
      controller: 'did:key:zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn',
      publicKeyBase58: '22TRL2fU4YR5xUPUy4dkrNKzNSG4jnAW1Z2qhuikcJmt4'
    }
  ],
  authentication: [ '#zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn' ],
  assertionMethod: [ '#zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn' ],
  capabilityInvocation: [ '#zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn' ],
  capabilityDelegation: [ '#zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn' ]
}
{
  kty: 'EC',
  crv: 'secp256k1',
  x: 'c2YjNcTXQFw-Z2Eq7I8ZWytaREDEoBfL8EQN3RPl47k',
  y: 'VEnaTTZ_RXfaOtviQILHLfjGxP39MMo2PCr1F9TPwkU',
  kid: 'ihlLyX3kHvlQPRWGuQ-eSfYI0iyO9s10ReAxWBtY_T8'
}
```

Any suggestions on which side the issue is? I would guess some crypto libraries work differently in browser / mobile.

**Comment by OR13** [comment]
I suggest not making network requests when resolving did key... the universal resolver is not needed to convert the DID to the did document for did key.

Take a look at https://github.com/decentralized-identity/jsonld-document-loader#usage

You should hook did resolution for did key, and save yourself a network request..

https://github.com/w3c-ccg/security-vocab/blob/master/js/__fixtures__/documentLoader.js#L55

**Comment by OR13** [comment]
You may want to request `did+json` or `did+ld+json` depending on the verification method encoding that is most convenient for you... but in either case... you should never be making a network request to resolve did-key... https://did.key.transmute.industries/did:key:zQ3shnQaLsowXs4JqiVAPSiduBvMp62Fi4iYYUxbWD4RjXFjn

**Comment by alexkravets** [comment]
Yes, that's clear. I'm not doing request in practice. But bumped into this problem on mobile, while researching on that decided to check with universal resolver and got same issue there. That's why I'm referencing it here.

**Comment by OR13** [comment]
hmm, its probably sad Buffer / string encoding issues in RN.... I am not sure if its possible, but I would love to have some RN tests for https://github.com/transmute-industries/did-key.js/tree/master/packages/test-vectors/src/did-core-conformance

That would essentially confirm the behavior of node / browser resolvers on mobile.

Something like react-native-did-key, and used the test vectors, and handled any other crypto / module issues in a nicer way for react native developers...

**Comment by alexkravets** [comment]
So the issue was due to the cached files by metro. Problem solved on my side. I'll close this and if we need to add support for universal resolver that would be PR for other repo.
